Movie/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Movie.Data;
using Movie.Models;
using Movie.ViewModels;

namespace Movie.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _db;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public CategoryController(AppDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _db.Categories;
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateCategoryViewModel obj) {
            if(ModelState.IsValid)
            {
                string fileName = UploadPicture(obj);
                Category cat = new Category
                {
                    Name = obj.Name,
                    Description = obj.Description,
                    CatImage = fileName,
                    CreatedDate = DateTime.Now
                };
                _db.Add(cat);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        private string UploadPicture(CreateCategoryViewModel obj)
        {
            string fileName = null;

            if (obj.CatImage != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                fileName = Guid.NewGuid().ToString() + "-" + obj.CatImage.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    obj.CatImage.CopyTo(fileStream);
                }
            }

            return fileName;
        }

        public IActionResult Edit(Guid id)
        {
            if (id != Guid.Empty)
            {
                Category obj = _db.Find<Category>(id);
                return View(obj);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EditPost(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            if (id != Guid.Empty)
            {
                Category obj = _db.Find<Category>(id);
                return View(obj);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeletePost(Category obj)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<Film> films = _db.Films.Where(f => f.CategoryId == obj.Id);
                foreach(var film in films)
                {
                    film.CategoryId = Guid.Empty;
                }
                _db.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Single(Guid id)
        {
            if (id != Guid.Empty)
            {
                Category obj = _db.Find<Category>(id);
                IEnumerable<Film> movies = _db.Films.Where(f => f.CategoryId == obj.Id);

                SingleCategoryViewModel vm = new SingleCategoryViewModel
                {
                    category = obj,
                    movies = movies,
                    tripletsNum = Math.Ceiling((double)movies.Count() / 3)
                };
                return View(vm);
            }
            return RedirectToAction("Index");
        }
    }
}

Movie/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Movie.Data;
using Movie.Models;
using Movie.ViewModels;

namespace Movie.Controllers
{
    public class MovieController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public MovieController(AppDbContext db, IWebHostEnvironment webHost)
        {
            _db = db;
            _webHostEnvironment = webHost;
        }

        public IActionResult Index()
        {
            IEnumerable<Film> movies = _db.Films;
            foreach(var movie in movies)
            {
                var catId = movie.CategoryId;
                if(catId != Guid.Empty) { 
                    ViewData[movie.Name] = _db.Categories.FirstOrDefault(cat => cat.Id == catId).Name;
                } else
                {
                    ViewData[movie.Name] = "Category Deleted";
                }
            }
            
            return View(movies);
        }

        public IActionResult Create()
        {
            ViewData["Categories"] = _db.Categories;
            return View(new CreateMovieViewModel());
        }

        [HttpPost]
        public IActionResult Create(CreateMovieViewModel obj)
        {
            if (ModelState.IsValid)
            {
                string fileName = UploadPicture(obj);
                Film film = new Film
                {
                    CategoryId = obj.CategoryId,
                    Name = obj.Name,
                    Description = obj.Description,
                    FilmImage = fileName,
                    CreatedDate = DateTime.Now
                };
                _db.Add(film);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        private string UploadPicture(CreateMovieViewModel obj)
        {
            string fileName = null;

            if(obj.FilmImage != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                fileName = Guid.NewGuid().ToString() + "-" + obj.FilmImage.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    obj.FilmImage.CopyTo(fileStream);
                }
            }

            return fileName;
        }

        public IActionResult Edit(Guid id)
        {
            if (id != Guid.Empty)
            {
                Film obj = _db.Find<Film>(id);
                
                EditMovieViewModel vm = new EditMovieViewModel()
                {
                    Id = obj.Id,
                    Name = obj.Name,
                    CategoryId = obj.CategoryId
                };
                ViewData["Categories"] = _db.Categories;

                return View(vm);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EditPost(Film obj)
        {
            if (ModelState.IsValid)
            {
                _db.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            if (id != Guid.Empty)
            {
                Film obj = _db.Find<Film>(id);

                return View(obj);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeletePost(Film obj)
        {
            if (ModelState.IsValid)
            {
                _db.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Single(Guid id)
        {
            if (id != Guid.Empty)
            {
                Film obj = _db.Find<Film>(id);
                Category cat = _db.Find<Category>(obj.CategoryId);

                SingleMovieViewModel vm = new SingleMovieViewModel()
                {
                    movie = obj,
                    category = cat
                };

                return View(vm);
            }
            return RedirectToAction("Index");
        }
    }
}

Movie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movie</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movie.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" disabled href="#">About</a>
                </li>
                <li class="nav-item dropdown" disabled>
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                  </div>
                </li>
              </ul>
              <form class="d-flex" disabled>
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Movie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>